### ISSUE TITLE
ImportError: No module named guidedfilter

### ISSUE THREAD

**Issue by lornezhao** [crisb-DUT/DnCNN-tensorflow#5]
when I run main.py,the error shows up.How could I fix it?
ps: I have tried pip or conda,it doesn't work.

**Comment by goonder** [comment]
I find the soluton....

**Comment by crisb-DUT** [comment]
You could comment it. I am sorry for the dirty source code, I will clean it in later Oct.

**Comment by lornezhao** [comment]
ZeroDivisionError: integer division or modulo by zero
what about this error?

**Comment by lornezhao** [comment]
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    tf.app.run()
  File "/home/lorne/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 42, in main
    model.train()
  File "/media/lorne/UUI/DnCNN-tensorflow-master/model.py", line 182, in train
    self.evaluate(epoch, counter, test_data)
  File "/media/lorne/UUI/DnCNN-tensorflow-master/model.py", line 319, in evaluate
    avg_psnr = psnr_sum / len(test_data)
ZeroDivisionError: integer division or modu

**Comment by BeibiKissU** [comment]
I saw the entrie code. It seems u don't need that guided filter. u could just #it.
