### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hiliusong** [crisb-DUT/DnCNN-tensorflow#51]
I run the main.py,but there are still some errors even some error is to random.py.  why?I am a littlewhite,Wish some good people could help me,3x!

(base) C:\Users\liu\Downloads\DnCNN-tensorflow-master>python model.py

(base) C:\Users\liu\Downloads\DnCNN-tensorflow-master>python main.py
GPU

Traceback (most recent call last):
  File "main.py", line 88, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 60, in main
    model = denoiser(sess)
  File "C:\Users\liu\Downloads\DnCNN-tensorflow-master\model.py", line 39, in __init__
    self.dataset = dataset(sess)
  File "C:\Users\liu\Downloads\DnCNN-tensorflow-master\model.py", line 202, in __init__
    random.shuffle(ind)
  File "C:\ProgramData\Anaconda3\lib\random.py", line 274, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'range' object does not support item assignment

**Comment by RevenKang** [comment]
You used Python3, In Python3  'range' object does not a list.

**Comment by RavenKang** [comment]
You are using python3. In python3 'range' object does not a list.
You should change `ind = range(len(filepaths))` to `ind = list(range(len(filepaths)))`

**Comment by hiliusong** [comment]
Thank you very much!
Best regards,
Song Liu




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"RavenKang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 下午5:28
收件人:&nbsp;"wbhu/DnCNN-tensorflow"<DnCNN-tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"经常不上qq"<7172217@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wbhu/DnCNN-tensorflow] help (#51)




You are using python3. In python3 'range' object does not a list.
 You should change ind = range(len(filepaths)) to ind = list(range(len(filepaths)))
