### ISSUE TITLE
I　get "MemoryError"

### ISSUE THREAD

**Issue by Tian14267** [crisb-DUT/DnCNN-tensorflow#7]
when I run 'generate_patches.py',I get this error.
Traceback (most recent call last):
  File "/home/tian/tensorflow/example/Denoising/DnCNN-tensorflow-master/generate_patches.py", line 100, in <module>
    generate_patches()
  File "/home/tian/tensorflow/example/Denoising/DnCNN-tensorflow-master/generate_patches.py", line 91, in generate_patches
    inputs = inputs / 255.0  # normalize to [0, 1]
MemoryError

I have no GPU,and my computer memory is 10GB.

**Comment by crisb-DUT** [comment]
Hi @Tian14267 ,

I think the reason is the memory is too small. Maybe you could try it with a smaller training set. Besides, generate_patches.py has nothing to do with GPU.

Thanks,
Wenbo
